# Generated by Django 3.0.5 on 2020-05-02 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0005_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=500)),
                ('listed_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('duplicate', 'Duplicate'), ('not a bug', 'Not a Bug'), ('open', 'Open'), ('fixed', 'Fixed'), ('retesting', 'Re-testing'), ('verified', 'Verified'), ('closed', 'Closed')], default='New', max_length=15)),
                ('description', models.CharField(max_length=10000)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BugTracker.Project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-listed_on'],
            },
        ),
    ]
