# Generated by Django 3.0.5 on 2020-05-02 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0006_bugs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bugs',
            new_name='Bug',
        ),
    ]
