# Generated by Django 3.0.5 on 2020-05-08 22:06

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0013_auto_20200509_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
