# Generated by Django 3.0.5 on 2020-05-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0014_auto_20200509_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='heading',
            field=models.CharField(max_length=500),
        ),
    ]
