# Generated by Django 3.0.5 on 2020-05-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0015_auto_20200509_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='cur_yr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='enr_no',
            field=models.BigIntegerField(null=True),
        ),
    ]
