# Generated by Django 3.0.5 on 2020-05-20 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0017_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
