# Generated by Django 3.0.5 on 2020-05-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0018_remove_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='enr_no',
            field=models.BigIntegerField(default=1),
        ),
    ]
