# Generated by Django 3.0.5 on 2020-06-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0021_auto_20200528_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='launched',
            field=models.BooleanField(default=0),
        ),
    ]
