# Generated by Django 3.0.5 on 2020-06-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0023_auto_20200604_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_media'),
        ),
    ]
