# Generated by Django 3.0.5 on 2020-06-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0026_auto_20200612_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tagIssues', to='BugTracker.Tag'),
        ),
    ]
