# Generated by Django 3.0.5 on 2020-06-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0028_auto_20200612_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='bug',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tagIssues', to='BugTracker.Tag'),
        ),
    ]
